### ISSUE TITLE
how to categorize: sleeping function called in invalid text

### ISSUE THREAD

**Issue by XingGaoY** [chyyuu/rt-patch-analysis#1]
Most rt roll back has not been reported as a bug yet, but some did. Maybe a rt bug is needed.

**Comment by XingGaoY** [comment]
Most rt roll back has not been reported as a bug yet, but some did. Maybe a rt bug is needed.

**Comment by XingGaoY** [comment]
more patches are found might report bug or warning with mightsleep, maybe a bug type "mightsleep". and the fix method is not preempt, but I simply use it. Those patches need revisit.

**Comment by chyyuu** [comment]
might_sleep的问题在现象上是系统在运行时出现warning/error信息，如果把问题想的严重一点，可以理解后果为kernel crash了。bug的type是deadlock，英文在atomic context中可能会sleep，这会导致deadlock风险。fix bug的方法有不同。所以，我个人觉得目前的分类可以不用添加mightsleep bug类型。@杨兴杲
